enum Permission {
    VIEW_ROLES = 'VIEW_ROLES',
    DELETE_ROLES = 'DELETE_ROLES',
    UPDATE_ROLES = 'UPDATE_ROLES',
    ADD_ROLES = 'ADD_ROLES',
    GIVE_ROLE = 'GIVE_ROLE',
    REMOVE_ROLE = 'REMOVE_ROLE',

    VIEW_USERS = 'VIEW_USERS',
    UPDATE_USERS = 'UPDATE_USERS',

    VIEW_MEETINGS = 'VIEW_MEETINGS',
    UPDATE_MEETINGS = 'UPDATE_MEETINGS',
    DELETE_MEETINGS = 'DELETE_MEETINGS',
    ADD_MEETINGS = 'ADD_MEETINGS',
}

export default Permission;
